name: Build Duck Launcher
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Application
        run: |
          npm install -g nativefier
          # Create a specific directory for the build
          mkdir build
          # Build index.html into the 'build' folder
          nativefier --name "Duck Launcher" "file://${{ github.workspace }}/index.html" --platform "windows" ./build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Duck-Launcher-Windows
          # Upload everything inside the build folder
          path: build/
